import type { Metadata } from "next";
import { Arimo, Inter } from "next/font/google";
import {Providers} from "./providers";
import { motion } from "framer-motion";

import "./globals.css";

const inter = Arimo({ weight: '600', subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jimmy Kolev",
  description: "Generated by create next app",
};

const variants = {
  hidden: { opacity: 0, x: -200, y: 0 },
  enter: { opacity: 1, x: 0, y: 0 },
  }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      
      <body className={inter.className}>

      <Providers>{children}</Providers>
      </body>
     
    </html>
  );
}
